apiVersion: v1
appVersion: 2.16.0.1-b7
version: 2.16.0
home: https://www.yugabyte.com
description: YugabyteDB Anywhere provides deployment, orchestration, and monitoring for managing YugabyteDB clusters. YugabyteDB Anywhere can create a YugabyteDB cluster with multiple pods provided by Kubernetes or OpenShift and logically grouped together to form one logical distributed database.
name: yugaware
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- name: Ram Sri
  email: ram@yugabyte.com
- name: Arnav Agarwal
  email: arnav@yugabyte.com
