apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-yugaware-pdb
spec:
  maxUnavailable: {{ .Values.yugaware.podDisruptionBudget.maxUnavailable | toJson }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-yugaware
